spring:
  application:
    name: skillbox-books
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: local_user
    password: local_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 1d
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html